# Configuration of codeclimate-Mantainability checks

# required to adjust maintainability checks
version: "2"

# 10/10 basic Manatainability checks
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: null
  identical-code:
    enabled: true
    config:
      threshold: null

# plugin is extra check
plugins:
  # eslint offers linting, complexity analysis, 
  # and style checking for EcmaScript/JavaScript code.
  eslint:
    enabled: true
    channel: "stable"


exclude_patterns:
- "config/"
- "db/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "Tests/"
- "**/vendor/"
- "**/*_test.go"
- "**/*.d.ts"