---
#############################
#############################
## JavaScript Linter rules ##
#############################
#############################

############
# Env Vars #
############
env:
  browser: true
  es6: true
  jest: true

###############
# Global Vars #
###############
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

ignorePatterns:
  - "!.*"
  - "**/node_modules/.*"

###############
# Parser vars #
###############
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module

###########
# Plugins #
###########
plugins:
  - '@typescript-eslint'

#########
# Rules #
#########
rules: 
    no-mixed-spaces-and-tabs: error
    no-trailing-spaces: error
    camelcase: error
    for-direction: error
    no-await-in-loop: error
    no-irregular-whitespace: error
    arrow-body-style: [error, always]
    no-var: error
    prefer-const: error
    yoda: [error, never]
    brace-style: [error, 1tbs]
    indent: [error, 4]
    comma-dangle: [error, only-multiline]
    semi: [error, always]
    semi-spacing: [error, {before: false, after: true}]
  
  


##############################
# Overrides for JSON parsing #
##############################
overrides:

  # JSON files
  - files:
      - "*.json"
    extends:
      - plugin:jsonc/recommended-with-json
    parser: jsonc-eslint-parser
    parserOptions:
      jsonSyntax: JSON

  # JSONC files
  - files:
      - "*.jsonc"
    extends:
      - plugin:jsonc/recommended-with-jsonc
    parser: jsonc-eslint-parser
    parserOptions:
      jsonSyntax: JSONC

  # JSON5 files
  - files:
      - "*.json5"
    extends:
      - plugin:jsonc/recommended-with-json5
    parser: jsonc-eslint-parser
    parserOptions:
      jsonSyntax: JSON5
