name: generate-documentation
run-name: Generate Documentation for all JS files in source
on:
  push:
  workflow_call:

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          ref: fortune-telling-dev
          path: main/fortune-telling-dev
          clean: false
      - run: rm -rf main/fortune-telling-dev/.git

      - name: Build Documentation
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: main/fortune-telling-dev/source
          publish_branch: documentation
          output_dir: ./out
          template: minami
          front_page: README.md
