name: generate-documentation
run-name: Generate Documentation using JSDoc
on:
  push:
    branches:
    - test-JSDoc

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Documentation
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./source
          output_dir: ./out
          # config_file: conf.json
          template: minami
          front_page: README.md

      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: documentation
          # destination_dir: subdir
          publish_dir: ./out
