name: generate-documentation
run-name: Generate Documentation for all JS files in source
on:
  push:
  workflow_call:

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          ref: fortune-telling-dev
          path: main/fortune-telling-dev
          clean: false
      - run: rm -rf main/fortune-telling-dev/.git

      - name: Build Documentation
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: main/fortune-telling-dev/source
          output_dir: ./out
          template: minami
          front_page: README.md
  
      - name: Place in Docs branch
        uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout documentation
          git add ./out/*
          git commit -m "updated docs"
          git push --set-upstream origin documentation


