name: Full CI/CD Pipeline

on:
    push:
        branches:
        - main
        - fortune-telling-dev
        - 8-ball
    workflow_dispatch:

permissions:
    contents: write
    pages: write
    id-token: write
    
jobs:
    linting:
        uses: ./.github/workflows/linter.yml
    testing:
        uses: ./.github/workflows/testing.yml
    documentation:
        uses: ./.github/workflows/documentation.yml
    build-gh-pages:
        uses: ./.github/workflows/jekyll-gh-pages.yml
        needs: [documentation, testing, linting]
