name: Full CI/CD Pipeline

on:
    push:
        branches: []
    
jobs:
    code-linting:
        runs-on: ubuntu-latest
        #TODO: Call codeclimate.yml
    testing:
        runs-on: ubuntu-latest
        #TODO: Create testing framework
    documentation:
        runs-on: ubuntu-latest
        #TODO: Call documentation.yml
    build-gh-pages:
        runs-on: ubuntu-latest
        #TODO: Call jekyll-gh-pages.yml
    