name: Full CI/CD Pipeline

on:
    push:
        branches: 
            - main
            - fortune-telling-dev
            - test-8ball-PWA

permissions:
    contents: read
    pages: write
    id-token: write
    
jobs:
    testing:
        uses: ./.github/workflows/testing.yml
    documentation:
        uses: ./.github/workflows/documentation.yml
    build-gh-pages:
        uses: ./.github/workflows/jekyll-gh-pages.yml
        needs: [documentation, testing]
