name: Full CI/CD Pipeline

on:
    push:
        branches: [main]
    
jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - name: Testing
              uses: actions/checkout@v3
            - run: echo "TODO Testing"
                #TODO: Create testing framework
    documentation:
        uses: ./.github/workflows/documentation.yml@v1
    build-gh-pages:
        uses: ./.github/workflows/jekyll-gh-pages.yml@v1
