name: Testing workflow

on:
    push:
        branches: [main, fortune-telling-dev]

jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                    node-version: 18
            - uses: actions/checkout@v3
              with:
                    ref: fortune-telling-dev
                    path: fortune-telling-dev
                    clean: false
            
            - run: npm ci
            - run: npm test
              
            



